In [1]:
import numpy as np,pandas as pd, matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [22]:
data=pd.read_csv('Advertising.csv') #to remove col 1 set header=0

In [23]:
data

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
5             6    8.7   48.9       75.0    7.2
6             7   57.5   32.8       23.5   11.8
7             8  120.2   19.6       11.6   13.2
8             9    8.6    2.1        1.0    4.8
9            10  199.8    2.6       21.2   10.6
10           11   66.1    5.8       24.2    8.6
11           12  214.7   24.0        4.0   17.4
12           13   23.8   35.1       65.9    9.2
13           14   97.5    7.6        7.2    9.7
14           15  204.1   32.9       46.0   19.0
15           16  195.4   47.7       52.9   22.4
16           17   67.8   36.6      114.0   12.5
17           18  281.4   39.6       55.8   24.4
18           19   69.2   20.5       18.3   11.3
19           20  147.3   23.9       19.1   14.6
20           21  218.4   27.7       53.4   18.0
21           22  237.4    5.1       23.5   12.5
22           23   13.2   15.9       49.6    5.6
23           24  228.3   16.9       26.2   15.5
24           25   62.3   12.6       18.3    9.7
25           26  262.9    3.5       19.5   12.0
26           27  142.9   29.3       12.6   15.0
27           28  240.1   16.7       22.9   15.9
28           29  248.8   27.1       22.9   18.9
29           30   70.6   16.0       40.8   10.5
..          ...    ...    ...        ...    ...
170         171   50.0   11.6       18.4    8.4
171         172  164.5   20.9       47.4   14.5
172         173   19.6   20.1       17.0    7.6
173         174  168.4    7.1       12.8   11.7
174         175  222.4    3.4       13.1   11.5
175         176  276.9   48.9       41.8   27.0
176         177  248.4   30.2       20.3   20.2
177         178  170.2    7.8       35.2   11.7
178         179  276.7    2.3       23.7   11.8
179         180  165.6   10.0       17.6   12.6
180         181  156.6    2.6        8.3   10.5
181         182  218.5    5.4       27.4   12.2
182         183   56.2    5.7       29.7    8.7
183         184  287.6   43.0       71.8   26.2
184         185  253.8   21.3       30.0   17.6
185         186  205.0   45.1       19.6   22.6
186         187  139.5    2.1       26.6   10.3
187         188  191.1   28.7       18.2   17.3
188         189  286.0   13.9        3.7   15.9
189         190   18.7   12.1       23.4    6.7
190         191   39.5   41.1        5.8   10.8
191         192   75.5   10.8        6.0    9.9
192         193   17.2    4.1       31.6    5.9
193         194  166.8   42.0        3.6   19.6
194         195  149.7   35.6        6.0   17.3
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [9]:
X=np.matrix(data.iloc[:,1:4].values)

In [10]:
X

matrix([[230.1,  37.8,  69.2],
        [ 44.5,  39.3,  45.1],
        [ 17.2,  45.9,  69.3],
        [151.5,  41.3,  58.5],
        [180.8,  10.8,  58.4],
        [  8.7,  48.9,  75. ],
        [ 57.5,  32.8,  23.5],
        [120.2,  19.6,  11.6],
        [  8.6,   2.1,   1. ],
        [199.8,   2.6,  21.2],
        [ 66.1,   5.8,  24.2],
        [214.7,  24. ,   4. ],
        [ 23.8,  35.1,  65.9],
        [ 97.5,   7.6,   7.2],
        [204.1,  32.9,  46. ],
        [195.4,  47.7,  52.9],
        [ 67.8,  36.6, 114. ],
        [281.4,  39.6,  55.8],
        [ 69.2,  20.5,  18.3],
        [147.3,  23.9,  19.1],
        [218.4,  27.7,  53.4],
        [237.4,   5.1,  23.5],
        [ 13.2,  15.9,  49.6],
        [228.3,  16.9,  26.2],
        [ 62.3,  12.6,  18.3],
        [262.9,   3.5,  19.5],
        [142.9,  29.3,  12.6],
        [240.1,  16.7,  22.9],
        [248.8,  27.1,  22.9],
        [ 70.6,  16. ,  40.8],
        [292.9,  28.3,  43.2],
        [112.9,  17.4,  38.6],
        

In [11]:
y=np.matrix(data.iloc[:,4:5].values)

In [12]:
y.shape

(200, 1)

In [13]:
y.reshape(200,)

matrix([[22.1, 10.4,  9.3, 18.5, 12.9,  7.2, 11.8, 13.2,  4.8, 10.6,
          8.6, 17.4,  9.2,  9.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6,
         18. , 12.5,  5.6, 15.5,  9.7, 12. , 15. , 15.9, 18.9, 10.5,
         21.4, 11.9,  9.6, 17.4,  9.5, 12.8, 25.4, 14.7, 10.1, 21.5,
         16.6, 17.1, 20.7, 12.9,  8.5, 14.9, 10.6, 23.2, 14.8,  9.7,
         11.4, 10.7, 22.6, 21.2, 20.2, 23.7,  5.5, 13.2, 23.8, 18.4,
          8.1, 24.2, 15.7, 14. , 18. ,  9.3,  9.5, 13.4, 18.9, 22.3,
         18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9, 14.2,  5.3, 11. ,
         11.8, 12.3, 11.3, 13.6, 21.7, 15.2, 12. , 16. , 12.9, 16.7,
         11.2,  7.3, 19.4, 22.2, 11.5, 16.9, 11.7, 15.5, 25.4, 17.2,
         11.7, 23.8, 14.8, 14.7, 20.7, 19.2,  7.2,  8.7,  5.3, 19.8,
         13.4, 21.8, 14.1, 15.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6,
         15.5,  7. , 11.6, 15.2, 19.7, 10.6,  6.6,  8.8, 24.7,  9.7,
          1.6, 12.7,  5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7,
         10.9, 19.2, 20.1, 10.4, 1

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [16]:
lr=LinearRegression()

In [17]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
lr.score(X_test,y_test)

0.8609466508230366

In [20]:
res=lr.predict(X_test)

In [21]:
res

array([[16.5653963 ],
       [21.18822792],
       [21.55107058],
       [10.88923816],
       [22.20231988],
       [13.35556872],
       [21.19692502],
       [ 7.35028523],
       [13.27547079],
       [15.12449511],
       [ 9.01443026],
       [ 6.52542825],
       [14.30205991],
       [ 8.97026042],
       [ 9.45679576],
       [12.00454351],
       [ 8.91549403],
       [16.15619251],
       [10.29582883],
       [18.72473553],
       [19.76821818],
       [13.77469028],
       [12.49638908],
       [21.53501762],
       [ 7.60860741],
       [ 5.6119801 ],
       [20.91759483],
       [11.80627665],
       [ 9.08076637],
       [ 8.51412012],
       [12.17604891],
       [ 9.9691939 ],
       [21.73008956],
       [12.77770578],
       [18.1011362 ],
       [20.07590796],
       [14.26202556],
       [20.93826535],
       [10.83938827],
       [ 4.38190607],
       [ 9.51332406],
       [12.40486324],
       [10.17045434],
       [ 8.09081363],
       [13.16388427],
       [ 5

In [24]:
help(lr)

Help on LinearRegression in module sklearn.linear_model.base object:

class LinearRegression(LinearModel, sklearn.base.RegressorMixin, sklearn.base.MultiOutputMixin)
 |  LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None)
 |  
 |  Ordinary least squares Linear Regression.
 |  
 |  Parameters
 |  ----------
 |  fit_intercept : boolean, optional, default True
 |      whether to calculate the intercept for this model. If set
 |      to False, no intercept will be used in calculations
 |      (e.g. data is expected to be already centered).
 |  
 |  normalize : boolean, optional, default False
 |      This parameter is ignored when ``fit_intercept`` is set to False.
 |      If True, the regressors X will be normalized before regression by
 |      subtracting the mean and dividing by the l2-norm.
 |      If you wish to standardize, please use
 |      :class:`sklearn.preprocessing.StandardScaler` before calling ``fit`` on
 |      an estimator with ``normalize=False

In [26]:
lr.coef_

array([[0.04405928, 0.1992875 , 0.00688245]])

In [28]:
lr.intercept_

array([2.70894909])